#docker compose for mysql server
version: '0.1'
services:
  db:
    image: mysql:latest
    ports:
      - "3307:3306"
    #restart: always
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE:  ${DB_DATABASE}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD:  ${DB_PASSWORD}
        #MYSQL_ROOT_USER: ${DB_USERNAME}

    volumes:
       - ./mysql:/var/lib/mysql
       - ./sql_scripts:/docker-entrypoint-initdb.d
networks:
  mynet:
    driver: bridge

